# Generated by Django 6.0.1 on 2026-01-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
